#!/usr/bin/env python3
"""
Day 67 - PDF Report
Demonstrates PDF report generation using reportlab
"""

import os
from pdf_generator import PDFGenerator, generate_sample_data, generate_sample_sales_data


def print_section(title: str):
    """Print section header"""
    print("\n" + "="*60)
    print(title)
    print("="*60)


def demo_sales_report():
    """Demonstrate sales report PDF"""
    print_section("1. SALES REPORT")
    
    pdf = PDFGenerator()
    pdf.create_report("output/sales_report.pdf", "Monthly Sales Report", "Python PDF Generator")
    
    pdf.add_paragraph("This report shows the monthly sales performance of our products.")
    pdf.add_spacer(0.3)
    
    sales_data = generate_sample_data()
    
    pdf.add_heading("Product Sales Summary", 2)
    pdf.add_table(
        sales_data,
        headers=['Product', 'Price (TRY)', 'Quantity', 'Total (TRY)']
    )
    
    total_revenue = sum(row[3] for row in sales_data)
    total_quantity = sum(row[2] for row in sales_data)
    
    pdf.add_paragraph(f"Total Revenue: {total_revenue:,.2f} TRY")
    pdf.add_paragraph(f"Total Items Sold: {total_quantity}")
    pdf.add_spacer(0.3)
    
    pdf.add_heading("Sales by Product", 2)
    products = [row[0] for row in sales_data[:6]]
    sales = [row[3] for row in sales_data[:6]]
    pdf.add_bar_chart(sales, products, "Revenue by Product (TRY)")
    
    pdf.add_heading("Revenue Distribution", 2)
    pdf.add_pie_chart(sales, products, "Revenue Share by Product")
    
    pdf.add_heading("Summary", 2)
    pdf.add_paragraph(f"Total Products: {len(sales_data)}")
    pdf.add_paragraph(f"Total Revenue: {total_revenue:,.2f} TRY")
    pdf.add_paragraph(f"Total Items Sold: {total_quantity}")
    pdf.add_paragraph(f"Average Revenue per Product: {total_revenue/len(sales_data):,.2f} TRY")
    
    pdf.add_footer("Sales Report - Generated by Python PDF Generator")
    
    pdf.save()
    print("[OK] Sales report generated successfully!")


def demo_employee_report():
    """Demonstrate employee report PDF"""
    print_section("2. EMPLOYEE REPORT")
    
    pdf = PDFGenerator()
    pdf.create_report("output/employee_report.pdf", "Employee Report", "Python PDF Generator")
    
    employees = [
        ['Alice Johnson', 'Engineering', 'Manager', 85000],
        ['Bob Smith', 'Engineering', 'Senior', 65000],
        ['Charlie Brown', 'Sales', 'Manager', 80000],
        ['Diana Prince', 'Sales', 'Senior', 60000],
        ['Eve Adams', 'Marketing', 'Lead', 70000],
        ['Frank Castle', 'Finance', 'Manager', 82000],
        ['Grace Hopper', 'Engineering', 'Lead', 72000],
        ['Henry Ford', 'Marketing', 'Senior', 55000]
    ]
    
    pdf.add_paragraph("This report shows the employee details and salary information.")
    pdf.add_spacer(0.3)
    
    pdf.add_heading("Employee Details", 2)
    pdf.add_table(
        employees,
        headers=['Name', 'Department', 'Position', 'Salary (TRY)']
    )
    
    total_salary = sum(row[3] for row in employees)
    avg_salary = total_salary / len(employees)
    departments = set(row[1] for row in employees)
    
    pdf.add_spacer(0.3)
    pdf.add_heading("Statistics", 2)
    pdf.add_paragraph(f"Total Employees: {len(employees)}")
    pdf.add_paragraph(f"Total Salary Budget: {total_salary:,.2f} TRY")
    pdf.add_paragraph(f"Average Salary: {avg_salary:,.2f} TRY")
    pdf.add_paragraph(f"Number of Departments: {len(departments)}")
    
    pdf.add_heading("Department Breakdown", 2)
    dept_counts = {}
    for emp in employees:
        dept = emp[1]
        dept_counts[dept] = dept_counts.get(dept, 0) + 1
    
    for dept, count in dept_counts.items():
        pdf.add_paragraph(f"  - {dept}: {count} employees")
    
    pdf.add_footer("Employee Report - Generated by Python PDF Generator")
    
    pdf.save()
    print("[OK] Employee report generated successfully!")


def demo_invoice_report():
    """Demonstrate invoice report PDF"""
    print_section("3. INVOICE REPORT")
    
    pdf = PDFGenerator()
    pdf.create_report("output/invoice_report.pdf", "Invoice Report", "Python PDF Generator")
    
    invoices = [
        ['INV-001', 'ABC Corp', '2026-01-15', 1500, 'Paid'],
        ['INV-002', 'XYZ Ltd', '2026-01-20', 2300, 'Pending'],
        ['INV-003', '123 Inc', '2026-01-25', 500, 'Paid'],
        ['INV-004', 'DEF Co', '2026-02-01', 3200, 'Overdue'],
        ['INV-005', 'GHI Group', '2026-02-10', 1800, 'Paid']
    ]
    
    pdf.add_paragraph("This report shows the invoice summary and payment status.")
    pdf.add_spacer(0.3)
    
    pdf.add_heading("Invoice Summary", 2)
    pdf.add_table(
        invoices,
        headers=['Invoice ID', 'Customer', 'Date', 'Amount (TRY)', 'Status']
    )
    
    total_amount = sum(row[3] for row in invoices)
    paid = sum(row[3] for row in invoices if row[4] == 'Paid')
    pending = sum(row[3] for row in invoices if row[4] == 'Pending')
    overdue = sum(row[3] for row in invoices if row[4] == 'Overdue')
    
    pdf.add_spacer(0.3)
    pdf.add_heading("Invoice Statistics", 2)
    pdf.add_paragraph(f"Total Invoices: {len(invoices)}")
    pdf.add_paragraph(f"Total Amount: {total_amount:,.2f} TRY")
    pdf.add_paragraph(f"Paid: {paid:,.2f} TRY ({paid/total_amount*100:.1f}%)")
    pdf.add_paragraph(f"Pending: {pending:,.2f} TRY ({pending/total_amount*100:.1f}%)")
    pdf.add_paragraph(f"Overdue: {overdue:,.2f} TRY ({overdue/total_amount*100:.1f}%)")
    
    pdf.add_heading("Status Distribution", 2)
    status_data = [paid, pending, overdue]
    status_labels = ['Paid', 'Pending', 'Overdue']
    pdf.add_pie_chart(status_data, status_labels, "Payment Status Distribution")
    
    pdf.add_footer("Invoice Report - Generated by Python PDF Generator")
    
    pdf.save()
    print("[OK] Invoice report generated successfully!")


def demo_product_report():
    """Demonstrate product inventory report PDF"""
    print_section("4. PRODUCT INVENTORY REPORT")
    
    pdf = PDFGenerator()
    pdf.create_report("output/inventory_report.pdf", "Inventory Report", "Python PDF Generator")
    
    inventory = [
        ['Laptop Pro', 'Electronics', 45, 50, 'In Stock'],
        ['Smartphone X', 'Electronics', 80, 100, 'In Stock'],
        ['Tablet Air', 'Computers', 15, 75, 'Low Stock'],
        ['Smart Watch', 'Accessories', 0, 200, 'Out of Stock'],
        ['Wireless Earbuds', 'Audio', 150, 300, 'In Stock'],
        ['Gaming Console', 'Gaming', 5, 40, 'Low Stock'],
        ['Monitor Ultra', 'Computers', 30, 60, 'In Stock'],
        ['Keyboard Mech', 'Accessories', 10, 150, 'Low Stock'],
        ['Mouse Pro', 'Accessories', 25, 200, 'In Stock'],
        ['External SSD', 'Computers', 90, 90, 'In Stock']
    ]
    
    pdf.add_paragraph("This report shows the current inventory status of all products.")
    pdf.add_spacer(0.3)
    
    pdf.add_heading("Product Inventory", 2)
    pdf.add_table(
        inventory,
        headers=['Product', 'Category', 'Current Stock', 'Max Stock', 'Status']
    )
    
    total_products = len(inventory)
    total_stock = sum(row[2] for row in inventory)
    low_stock = sum(1 for row in inventory if row[4] == 'Low Stock')
    out_of_stock = sum(1 for row in inventory if row[4] == 'Out of Stock')
    
    pdf.add_spacer(0.3)
    pdf.add_heading("Inventory Statistics", 2)
    pdf.add_paragraph(f"Total Products: {total_products}")
    pdf.add_paragraph(f"Total Stock Items: {total_stock}")
    pdf.add_paragraph(f"Low Stock Items: {low_stock}")
    pdf.add_paragraph(f"Out of Stock Items: {out_of_stock}")
    
    pdf.add_heading("Category Breakdown", 2)
    categories = {}
    for row in inventory:
        cat = row[1]
        categories[cat] = categories.get(cat, 0) + 1
    
    for cat, count in categories.items():
        pdf.add_paragraph(f"  - {cat}: {count} products")
    
    pdf.add_footer("Inventory Report - Generated by Python PDF Generator")
    
    pdf.save()
    print("[OK] Inventory report generated successfully!")


def main():
    print("=" * 60)
    print("DAY 67 - PDF REPORT")
    print("=" * 60 + "\n")
    
    # Create output directory
    os.makedirs("output", exist_ok=True)
    
    # Generate reports
    demo_sales_report()
    demo_employee_report()
    demo_invoice_report()
    demo_product_report()
    
    print("\n" + "="*60)
    print("[OK] ALL REPORTS GENERATED SUCCESSFULLY!")
    print("[OK] Check the 'output' folder for PDF files")
    print("="*60 + "\n")


if __name__ == "__main__":
    main()
